"use client";
import {useEffect,useState} from "react";
type E={id:number;expense_date:string;merchant:string;category:string;amount:number};type I={id:number;income_date:string;source:string;amount:number};type B={id:number;month_key:string;category:string;amount:number};
const money=(n:number)=>new Intl.NumberFormat("en-PK",{style:"currency",currency:"PKR",maximumFractionDigits:0}).format(n);
export default function Home(){const[t,setT]=useState("Dashboard"),[e,setE]=useState<E[]>([]),[i,setI]=useState<I[]>([]),[b,setB]=useState<B[]>([]),[x,setX]=useState(""),[a,setA]=useState(""),[s,setS]=useState(""),[ia,setIa]=useState(""),[c,setC]=useState("Household"),[ba,setBa]=useState(""),[err,setErr]=useState("");
const load=async()=>{try{const r=await Promise.all(["expenses","income","budgets"].map(z=>fetch("/api/"+z)));if(r.some(z=>!z.ok))throw Error("Database is not ready");setE(await r[0].json());setI(await r[1].json());setB(await r[2].json())}catch(z){setErr(z instanceof Error?z.message:"Error")}};useEffect(()=>{load()},[]);
const post=async(path:string,body:object)=>{const r=await fetch("/api/"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)setErr("Could not save data");else load()};
const spend=e.reduce((q,z)=>q+Number(z.amount),0),inc=i.reduce((q,z)=>q+Number(z.amount),0),plan=b.reduce((q,z)=>q+Number(z.amount),0);
const tabs=["Dashboard","Expenses","Income","Budget","Allowances","Fixed Payables","Loans & Credit","History & AI","Settings"];
return <main><aside><h1>My Household<br/>Expense</h1>{tabs.map(z=><button key={z} className={t===z?"active":""} onClick={()=>setT(z)}>{z}</button>)}</aside><section><header><div><p className="eyebrow">HOUSEHOLD FINANCE</p><h2>{t}</h2></div><button className="refresh" onClick={load}>Refresh</button></header>{err&&<p className="error">{err}</p>}
{t==="Dashboard"&&<><div className="cards"><Card l="Spending" v={money(spend)}/><Card l="Income" v={money(inc)}/><Card l="Balance" v={money(inc-spend)}/><Card l="Budget" v={money(plan)}/></div><div className="panel"><h3>Recent expenses</h3>{e.length?e.slice(0,8).map(z=><div className="row" key={z.id}><span><strong>{z.merchant}</strong><small>{z.category} · {z.expense_date}</small></span><b>{money(Number(z.amount))}</b></div>):<p>No expenses yet.</p>}</div></>}
{t==="Expenses"&&<div className="panel"><h3>Add expense</h3><div className="form"><input value={x} onChange={z=>setX(z.target.value)} placeholder="Merchant"/><input value={a} onChange={z=>setA(z.target.value)} type="number" placeholder="Amount PKR"/><button className="add" onClick={()=>{post("expenses",{merchant:x,amount:Number(a),category:"Other",member:"Saad"});setX("");setA("")}}>Save</button></div>{e.map(z=><div className="row" key={z.id}><span>{z.merchant}<small>{z.expense_date}</small></span><b>{money(Number(z.amount))}</b></div>)}</div>}
{t==="Income"&&<div className="panel"><h3>Add income</h3><div className="form"><input value={s} onChange={z=>setS(z.target.value)} placeholder="Income source"/><input value={ia} onChange={z=>setIa(z.target.value)} type="number" placeholder="Amount PKR"/><button className="add" onClick={()=>{post("income",{source:s,amount:Number(ia),member:"Household"});setS("");setIa("")}}>Save</button></div>{i.length?i.map(z=><div className="row" key={z.id}><span>{z.source}<small>{z.income_date}</small></span><b>{money(Number(z.amount))}</b></div>):<p>No income recorded.</p>}</div>}
{t==="Budget"&&<div className="panel"><h3>Monthly budget</h3><div className="form"><input value={c} onChange={z=>setC(z.target.value)} placeholder="Category"/><input value={ba} onChange={z=>setBa(z.target.value)} type="number" placeholder="Budget PKR"/><button className="add" onClick={()=>{post("budgets",{category:c,amount:Number(ba),monthKey:new Date().toISOString().slice(0,7)});setBa("")}}>Save</button></div>{b.length?b.map(z=><div className="row" key={z.id}><span>{z.category}<small>{z.month_key}</small></span><b>{money(Number(z.amount))}</b></div>):<p>No budget categories yet.</p>}</div>}
{!["Dashboard","Expenses","Income","Budget"].includes(t)&&<div className="panel"><h3>{t}</h3><p>Next build phase.</p></div>}</section></main>}
function Card({l,v}:{l:string;v:string}){return <div className="card"><span>{l}</span><strong>{v}</strong></div>}